name: .NET Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore API & Test Dependencies
      run: |
        dotnet restore RfidAccessControl.Api/RfidAccessControl.Api.csproj
        dotnet restore RfidAccessControl.Tests/RfidAccessControl.Tests.csproj

    - name: Build API
      run: dotnet build RfidAccessControl.Api/RfidAccessControl.Api.csproj --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test RfidAccessControl.Tests/RfidAccessControl.Tests.csproj --no-restore --verbosity normal